= Tournament app

Travis CI : image:https://travis-ci.com/ncomet/tournament.svg?token=zjERHfQ93xyr8dzuPZod&branch=master["Build Status", link="https://travis-ci.com/ncomet/tournament"]

* Domain Driven Design (DDD) implementation
* TDD implementation

== Note on branches

=== branch `master`

NOTE: Implementation that is made to scale up with increasing number of players

2 DynamoDB tables :

* `scores` (used for sorting & ranking players)
** Primary (HASH `entry` string, RANGE `score` number), `entry` will never change and value will always be "entry", `score` is used to store the score, and will always be sorted.
** One attribute `playerIds` : `Set<String>` the playersIds which have score `score`

* `players` (used for players info)
** Primary (HASH `id` string) `id` being the playerId that will be looked up after browsing `scores` table
** Attributes `nickname` string & `score` number (we replicate the score here for allPlayers view)

=== branch `one-table-inmemory-scoring`

NOTE: Simpler implementation, but can only handle a small number of players due to how DynamoDB hashes the keys

It only uses `players` table as described above in `master` branch.
Sorting is done in memory on scores after a full `scan()` of players table, which is inefficient if there is a large number of players, but easier since there is no synchronization to maintain between two tables.

== Prerequisites

* localstack installed and running
* `jdk8` or later

== Build & Start

to build and run all tests

[source,bash]
----
./gradlew build
----

to launch the app (dev mode)

[source,bash]
----
./runApp.sh
----

== Integration Tests

To run Karate integration tests while app is running

[source,bash]
----
cd it
./gradlew test
----

== HealthCheck

HealthCheck for DynamoDB availability : http://localhost:8080/health

== REST API doc

to access swagger API doc

http://localhost:8080/swagger

== Production

For production, the following environment variables need to be defined :

* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
* DYNAMODB_URI
* DYNAMODB_REGION

[source,bash]
----
./gradlew assemble
java -jar build/libs/tournament.jar server
----


